# Generated by Django 6.0.5 on 2026-05-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommissionProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_process", models.DateField(auto_now_add=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("soumis", "Soumis à SOLIDIS"),
                            ("accepte", "Accepté"),
                            ("rejete", "Rejeté"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                (
                    "reference_solidis",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-date_from"],
            },
        ),
        migrations.CreateModel(
            name="CommissionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idcredit", models.CharField(max_length=50)),
                ("lo_loan_id", models.IntegerField()),
                ("encours", models.DecimalField(decimal_places=2, max_digits=18)),
                ("commission", models.DecimalField(decimal_places=2, max_digits=18)),
                ("commission_type", models.CharField(max_length=30)),
                ("days_in_arrears", models.IntegerField()),
                ("report_date", models.DateField()),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="commission.commissionprocess",
                    ),
                ),
            ],
            options={
                "ordering": ["commission_type", "idcredit"],
            },
        ),
    ]
