# Generated by Django 6.0.5 on 2026-08-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolidisF2Declared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loloanid', models.FloatField(db_column='LOLOANID', null=True)),
                ('ref', models.TextField(db_column='REF', null=True)),
                ('id_credit', models.TextField(db_column='ID CREDIT', null=True)),
                ('cin', models.BigIntegerField(db_column='N° CIN', null=True)),
                ('date_de_naissance', models.TextField(db_column='DATE DE NAISSANCE', null=True)),
                ('genre', models.TextField(db_column='GENRE', null=True)),
                ('agence_octroi', models.TextField(db_column="AGENCE D'OCTROI", null=True)),
                ('objet', models.TextField(db_column='OBJET', null=True)),
                ('classt', models.TextField(db_column='CLASST', null=True)),
                ('montant', models.BigIntegerField(db_column='MONTANT', null=True)),
                ('datouv', models.DateField(db_column='DATOUV', null=True)),
                ('datech', models.DateField(db_column='DATECH', null=True)),
                ('cycle', models.BigIntegerField(db_column='CYCLE', null=True)),
                ('taux', models.FloatField(db_column='TAUX', null=True)),
                ('date_declaration', models.DateField(db_column='DATE_DECLARATION', null=True)),
            ],
            options={
                'db_table': 'Solidis_f2_declared_v2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeclarationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plafond_emg', models.DecimalField(decimal_places=2, default=5000000000, max_digits=18)),
                ('seuil_reprise_pct', models.DecimalField(decimal_places=4, default=0.8, max_digits=5)),
                ('f2_bloque', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Solidis_declaration_config',
            },
        ),
        migrations.CreateModel(
            name='DeclarationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_process', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis à SOLIDIS'), ('f2_bloque', 'F2 suspendu (EMG envoyé)'), ('sans_donnees', 'Aucune donnée EMG'), ('sans_soumission', 'Aucune soumission éligible'), ('echec', 'Échec')], default='en_cours', max_length=20)),
                ('reference_solidis', models.CharField(blank=True, max_length=100, null=True)),
                ('f2_bloque', models.BooleanField(default=False)),
                ('encours_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('emg_lignes', models.IntegerField(default=0)),
                ('emg_encours_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('f2_lignes', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Solidis_declaration_process',
                'ordering': ['-date_from'],
            },
        ),
    ]
