# Generated by Django 6.0.5 on 2026-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declarationprocess',
            name='encours_reference',
        ),
        migrations.AddField(
            model_name='declarationprocess',
            name='f2_lignes_exclues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationprocess',
            name='jours_f2_actifs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationprocess',
            name='jours_f2_bloques',
            field=models.IntegerField(default=0),
        ),
    ]
