# Generated by Django 6.0.5 on 2026-08-13 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0002_remove_declarationprocess_encours_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declarationprocess',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='declarationprocess',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='declarationprocess',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='declarationprocess',
            name='jours_f2_actifs',
        ),
        migrations.RemoveField(
            model_name='declarationprocess',
            name='jours_f2_bloques',
        ),
        migrations.AddField(
            model_name='declarationprocess',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
    ]
