# Generated by Django 6.0.5 on 2026-05-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolidisInitialLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loloanid", models.FloatField(db_column="LOLOANID", null=True)),
                ("ref", models.TextField(db_column="REF", null=True)),
                ("id_credit", models.TextField(db_column="ID CREDIT", null=True)),
                ("cin", models.BigIntegerField(db_column="N° CIN", null=True)),
                (
                    "date_de_naissance",
                    models.TextField(db_column="DATE DE NAISSANCE", null=True),
                ),
                ("genre", models.TextField(db_column="GENRE", null=True)),
                (
                    "agence_octroi",
                    models.TextField(db_column="AGENCE D'OCTROI", null=True),
                ),
                ("objet", models.TextField(db_column="OBJET", null=True)),
                ("classt", models.TextField(db_column="CLASST", null=True)),
                ("montant", models.BigIntegerField(db_column="MONTANT", null=True)),
                ("datouv", models.DateField(db_column="DATOUV", null=True)),
                ("datech", models.DateField(db_column="DATECH", null=True)),
                ("cycle", models.BigIntegerField(db_column="CYCLE", null=True)),
                ("taux", models.FloatField(db_column="TAUX", null=True)),
            ],
            options={
                "db_table": "Solidis_initial_loan_v2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SolidisLoanMonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idcredit", models.CharField(db_column="IDCREDIT", max_length=50)),
                ("lo_loan_id", models.IntegerField(db_column="loLoanID")),
                ("cin", models.CharField(db_column="CIN", max_length=30, null=True)),
                (
                    "encours",
                    models.DecimalField(
                        db_column="Encours", decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "days_in_arrears",
                    models.BigIntegerField(db_column="DaysInArrears", null=True),
                ),
                ("report_date", models.DateField(db_column="reportDate", null=True)),
            ],
            options={
                "db_table": "Solidis_loan_update_monthly_reports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProcesseAppelDeGarantie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_appel", models.DateField(auto_now_add=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("soumis", "Soumis à SOLIDIS"),
                            ("accepte", "Accepté"),
                            ("rejete", "Rejeté"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                (
                    "reference_solidis",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-date_from"],
            },
        ),
        migrations.CreateModel(
            name="LoanRepaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idcredit", models.CharField(max_length=50)),
                ("lo_loan_id", models.IntegerField()),
                (
                    "loan_amount_current",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "encours",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                ("days_in_arrears", models.IntegerField(null=True)),
                ("report_date", models.DateField(null=True)),
                ("repayment_date", models.DateField(null=True)),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("trx_id", models.IntegerField(null=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="garantie.processeappeldegarantie",
                    ),
                ),
            ],
            options={
                "ordering": ["idcredit", "repayment_date"],
            },
        ),
        migrations.CreateModel(
            name="ClientSituation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idcredit", models.CharField(max_length=50)),
                ("lo_loan_id", models.IntegerField()),
                ("encours", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "montant_appel_garanti",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("days_in_arrears", models.IntegerField()),
                ("report_date", models.DateField()),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situations",
                        to="garantie.processeappeldegarantie",
                    ),
                ),
            ],
            options={
                "ordering": ["idcredit"],
            },
        ),
    ]
